# -*- coding: utf-8 -*-
"""Projet Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_lAROnjc8-NxXosQ74XI3S-7qgU0u446
"""

#-- Importation du fichier
import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv("sales_financial_dataset.csv")
sales = pd.read_csv("sales_financial_dataset.csv")
sales.head()

#-- 1. Quelles catégories génerent le plus de revenus ?
sales.groupby("category")["net_revenue"].sum().sort_values(ascending = False)

#-- 2. Quelles produits ont la meilleure marge moyenne ?
sales.groupby("product_name")["margin_pct"].mean().sort_values(ascending= False)

#-- 3. Quelle est la contribution de chaque région au chiffre d’affaires total ?
region_revenue = df.groupby("region")["net_revenue"].sum()
region_contribution = (region_revenue / region_revenue.sum()) * 100
region_contribution.sort_values(ascending=False)

region_contribution.sort_values(ascending=False).plot(kind="bar")

import matplotlib.pyplot as plt
plt.title("Contribution des régions au chiffre d'affaires (%)")
plt.ylabel("Pourcentage")
plt.show()

#-- 4. Quelle est l'évolution mensuelle du chiffre d'affaires ?
sales["sale_date"] = pd.to_datetime(sales["sale_date"])
monthly_revenue = sales.groupby(sales["sale_date"].dt.to_period("M"))["net_revenue"].sum()
monthly_revenue.plot()
plt.title("Évolution mensuelle du chiffre d'affaires")
plt.xlabel("Mois")
plt.ylabel("Chiffre d'affaires")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#-- 5. Est ce que vendre plus signifie être plus rentable ?
sales[["net_revenue", "margin_pct"]].corr()
plt.scatter(sales["net_revenue"], sales["margin_pct"])
plt.xlabel("Chiffre d'affaires")
plt.ylabel("Marge (%)")
plt.title("Relation entre chiffre d'affaires et marge")
plt.show()

#-- 6. Quel est le panier moyen par client ?
avg_basket = sales.groupby("client_name")["net_revenue"].mean().sort_values(ascending=False)
avg_basket

#--7. Quelle est la dispersion du chiffre d’affaires ?
sales["net_revenue"].describe()
sales["net_revenue"].hist(bins=30)
plt.title("Distribution du chiffre d'affaires")
plt.xlabel("Chiffre d'affaires")
plt.ylabel("Fréquence")
plt.show()